### PR TITLE
use window.location for ws url and tunnel when api_proxy in use

### PR DESCRIPTION
**Pull request by sean-brandt**
Leverage window.location for the URL to communicate with, and when api_proxy is enabled, use that.

Requires that the nginx config be updated as well ( not in this patch ) with contents similar to:

```
# upstream def for websocket
upstream ws_upstream {
  server 127.0.0.1:4202;
}
```

```
# location for websocket
location /websocket {
    proxy_pass https://ws_upstream;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 7d;
}
```

### CODE REVIEW

**Comment by lynnfaraday** [comment]
I'm afraid I can't merge this change.  It loses important configuration options, like the explicit configuration of the websocket port.   What problem were you trying to address?

**Comment by sean-brandt** [comment]
Hmm, I missed the check on the websocket port in play.js it seems, which I can address.

The current approach relies on the game to tell, through an exchange of config data, something that the website already knows - the host, at least, that the game is on. And when doing API tunneling, there's a gap in that the websocket connection still requires a separate port without really needing to.

You can tunnel websocket connections just like the API connection is tunneled, and that was the primary goal of this patch. 

The web portal port is really not necessary - given that the browser is already talking to it.

The websocket port is needed if not being tunneled, which if we use the ```aresconfig.use_api_proxy``` config switch we can determine if tunneling is enabled at all.

If tunneling, then ideally tunneling both the websocket and API server communications would be ideal, thus limiting the browser communication to a single port.

I've pushed an update to this branch that contains a fix for when the api proxy is not being used ( in play.js ), which covers the gap you noticed I think?

That said, with the PR closed - I'd have to delete this branch and open it again, if you are interested in seeing the change.

**Comment by lynnfaraday** [comment]
I appreciate the suggestion, but I'm going to pass, thanks.  Getting rid of a sometimes-unnecessary port is not really worth the additional burden of making people fiddle with their nginx config.  That is intimidating for the sort of novice system admin that Ares is designed to support.

**Comment by sean-brandt** [comment]
Okie. Taken into scope with an update to the nginx template in aresmush during install, I didn't think it an overly large change. 

Obviously your call, however :) 

Please let me know if you've a preferred method of PRs/suggestions. I'm excited about what you've built here and hope to be able to help out as I work on standing up a game as well.

**Comment by lynnfaraday** [comment]
At this point, Ares is really a personal pet project and not a fully open-source team.  Bug reports and suggestions are always welcome on the forums, and if you want to point to a commit you've done on a branch for reference I will certainly take a look.  I credit all ideas and contributions in the release notes.

**Comment by lynnfaraday** [comment]
@sean-brandt  I took another look at this and think I misunderstood what you'd done the first time I looked at it.  You're right - it can be incorporated into the default nginx config pretty easily.  I will look at pulling these changes into the next patch, thanks.

Also I think my last comment came across like I didn't want PRs, which was not the intention.  You're welcome to submit contributions via PR or any other means if it's something you've done on your own game and want to share.  I was just trying to say that I wasn't farming out "assignments" from the Ares backlog or anything.  Sorry for any confusion!

Btw - if you have an Ares Central forum account I can PM you an invite to the Ares Discord channel (currently private).

**Comment by sean-brandt** [comment]
Sure, sounds good.  I'm a discord fan.

My forum account is: @Sordin

**Pull request closed without merging**
