### PR TITLE
Use a URI relative host for building websocket urls and game host

### PR DESCRIPTION
**Pull request by sean-brandt**
If the server is set up on an AWS host, or any other host, where NAT may be involved the configured server host value is never going to be correct.

Change the way the host is determined to use the IP that the website is being served from to leverage 
```window.location.protocol```

### CODE REVIEW

**Comment by sean-brandt** [comment]
Hmm, more thought - better approach will be likely to allow for a different 'bind' address to be configured. server.host is spread throughout the codebase too far.

**Comment by sean-brandt** [comment]
Hmm, more thought - better approach will be likely to allow for a different 'bind' address to be configured. server.host is spread throughout the codebase too far.

**Comment by sean-brandt** [comment]
The big miss is that the server.host config parameter defines a hostname/IP address that currently must be what matches what the outside world uses to connect to the server _AND_ what the server binds to locally

This doesn't work when the server is running on a private network and has a non routable ( rfc1918 address , 192.168.x.x, etc ) as would be the case on any servers running in AWS ( EC2 or Lightsail ) where the private IPs are different than the public ips. 

There needs to be an ability to specify a bind address in that situation. I'm working on a patch for the core game, as well as for the web portal to support both that, and running over SSL as well.

**Comment by lynnfaraday** [comment]
Nothing in the Ares configuration itself relies on an IP address.  You just make server.host the hostname, and everything derives from that.

Or are you saying that something under the hood in EventMachine is messed up if the private IP is different than the public IP?

I already have support for SSL coming in the next patch, FYI.

**Comment by sean-brandt** [comment]
Yes. If I have a server that has an IP address ( private ) of 10.1.1.1 and a public IP of 53.1.1.1 and a dns name of test-ares.aresmush.com that points to 53.1.1.1

If I configure server.host today to be test-ares.aresmush.com, the game won't start cause it can't bind locally to 53.1.1.1

If I configure server.host to 10.1.1.1 it will start, but the web portal will be broken because it can't get to the server using 10.1.1.1

The fix for that appears to be very trivial, introducing a ```bind_address``` server.yml optional config parameter, then allowing that to override the value of ```host``` only in ```engine/aresmush/server.rb```

**Comment by lynnfaraday** [comment]
Ah okay - I get it now.  And yes, I will add a bind_address parameter.  Thanks for identifying the issue (and the fix).

**Pull request closed without merging**
